### ISSUE TITLE
Planned dates in Incoming Mobilities API but not in Outgoing Mobilities API

### ISSUE THREAD

**Issue by spinho-uporto** [erasmus-without-paper/ewp-specs-api-imobilities#10]
The planned dates are present in the Incoming Mobilities API v2 but not in the Outgoing Mobilities API v3. Shouldn't the sending HEI be responsible for setting those dates?"

**Comment by kamil-olszewski-uw** [comment]
Moving planned dates from Outgoing Mobilities API to Incoming Mobilities API is planned for a future major release of both APIs. This change is needed because the receiving HEI is the business owner of this information and informs the student of the planned dates (the sending HEI only sets the academic term for mobility). After all, it's a common practice for the receiving HEI to provide accepted students with an official letter of admission/confirmation of acceptance - in this document, receiving HEI states the exact dates the student has been admitted to (this document is often used by sending HEI to calculate the grant). So up until now, the receiving HEI set the dates, informed the student (eg. by e-mail or in the mentioned document), the student passed this information to sending HEI, which sent it back to the receiving HEI via EWP. The planned change clearly fixes this process.
